"""init documents chunks ingestion_runs

Revision ID: 58ea9e981eff
Revises: 
Create Date: 2026-10-03 09:52:53.693233
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '58ea9e981eff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.Enum('tutorial', 'how_to', 'concept', 'api_reference', 'other', name='doctype', native_enum=False, length=24), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'superseded', 'deleted', name='docstatus', native_enum=False, length=24), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('library', 'version', 'source_path', name='library_version_path')
    )
    op.create_index('ix_documents_filter', 'documents', ['library', 'version', 'status'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('parent_chunk_id', sa.String(length=40), nullable=True),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('heading_path', sa.Text(), nullable=False),
    sa.Column('heading_path_list', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('has_code', sa.Boolean(), nullable=False),
    sa.Column('code_languages', sa.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('index_status', sa.Enum('pending', 'indexed', 'failed', 'stale', 'not_indexed', name='indexstatus', native_enum=False, length=24), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('index_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level >= 0', name=op.f('ck_chunks_level_nonneg')),
    sa.CheckConstraint('token_count >= 0', name=op.f('ck_chunks_tokens_nonneg')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['chunks.chunk_id'], name=op.f('fk_chunks_parent_chunk_id_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('document_id', 'strategy', 'level', 'chunk_index', name='doc_strategy_level_idx')
    )
    op.create_index('ix_chunks_doc_strategy', 'chunks', ['document_id', 'strategy'], unique=False)
    op.create_index('ix_chunks_parent', 'chunks', ['parent_chunk_id'], unique=False)
    op.create_index('ix_chunks_sync', 'chunks', ['strategy', 'is_leaf', 'index_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_sync', table_name='chunks')
    op.drop_index('ix_chunks_parent', table_name='chunks')
    op.drop_index('ix_chunks_doc_strategy', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_documents_filter', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###